config/routes.rb
Rails.application.routes.draw do
  get 'workgroup', to: 'workgroups#index'
  post 'workgroup', to: 'workgroups#create'
  delete 'workgroup/:id', to: 'workgroups#destroy'
  get 'workgroup/user/:id', to: 'workgroups#get_user'
  
  resources :publications, only: [:create, :destroy]
  resources :companies, only: [:new, :create]
  resources :campaigns, except: [:index]
  
  get 'dashboard', to: 'dashboard#index'
  get 'fuckoff', to: 'publications#fuckoff'

  devise_for :users

  devise_scope :user do
    get 'auth/:provider/callback', to: 'sessions#assign'
    
    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/company.rb
class Company < ApplicationRecord
    validates :name, presence: true
    validates :package, presence: true
    has_many :users
    has_many :campaigns

    def twitter
        @client ||= Twitter::REST::Client.new do |config|
            config.consumer_key        = 'NcViuuBF5KGewVIZDjXgNB0pY'
            config.consumer_secret     = 'ZT44eCKhG1YrniME9KcPQiKAFnG4ZPQdG5kTjlN4PsrbNW9qTd'
            config.access_token        = token
            config.access_token_secret = secret
        end
    end

    def pinterest      
        ravi = 'AgnVQhvySyQxVEz4FghI5E-UObg-Fdc1tI_TK-NGTyjcnuC4ZAQpQDAAAKqcRk8w2oJgusAAAAAA'
        mhm = 'AkSJ59zuWPN9IVsWbq5enGQR7Am7FddGxAmYJnpGTyjcnuC4ZApgwDAAAuKzRk9Tr5GgyvwAAAAA'
        @client ||= Pinterest::Client.new(ravi)
    end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
    def new
    end

    def create
        @company = Company.new(company_params)
        @user = @company.users.new(user_params)
        @user.update(is_admin: true)
        if @company.save 
            sign_in @user
            redirect_to '/auth/twitter/'
        else
            redirect_to '/', notice: @company.errors
        end
    end

    private

        def company_params
            params.require(:company).permit(:name, :package)
        end

        def user_params
            params.require(:user).permit(:username, :email, :password, :password_confirmation)
        end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/new.html.erb
<%= form_tag(companies_path, method: "post") do %>
<div class="wrapper">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <div class="card card-register">
          <div class="card-header primary-degraded">
            <h4 class="card-title text-white">Sign up</h4>
          </div>
          <div class="card-body row">
            <form class="form">
              <div class="col-md-6">
                <div class="input-group">
                  <div class="input-group-prepend">
                    <div class="input-group-text">
                      <i class="tim-icons icon-bank"></i>
                    </div>
                  </div>
                  <input class="form-control" autocomplete="off" placeholder="Organization name's" type="text" name="company[name]" id="company_name">
                </div>
                <div class="input-group">
                  <div class="input-group-prepend">
                    <div class="input-group-text">
                      <i class="tim-icons icon-badge"></i>
                    </div>
                  </div>
                  <%= text_field :user, :username, autocomplete: "off", class:"form-control", placeholder: "Name of the responsible" %>
                </div>
                <div class="input-group">
                  <div class="input-group-prepend">
                    <div class="input-group-text">
                      <i class="tim-icons icon-app"></i>
                    </div>
                  </div>
                  <select class="form-control" name="company[package]" id="company_package">
                    <option value="0" style="color: #000;">Select a package</option>
                    <option value="1" style="color: #000;">Basic (1 user)</option>
                    <option value="2" style="color: #000;">Pro (5 user)</option>
                    <option value="3" style="color: #000;">Business (15 user)</option>
                  </select>
                </div>
              </div>
              <!-- Derecha -->
              <div class="col-md-6">
                <div class="input-group">
                  <div class="input-group-prepend">
                    <div class="input-group-text">
                      <i class="tim-icons icon-email-85"></i>
                    </div>
                  </div>
                  <%= email_field :user, :email, autocomplete: "email", class:"form-control", placeholder: "Email" %>
                </div>
                <div class="input-group">
                  <div class="input-group-prepend">
                    <div class="input-group-text">
                      <i class="tim-icons icon-lock-circle"></i>
                    </div>
                  </div>
                  <%= password_field :user, :password, autocomplete: "current-password", class:"form-control", placeholder: "Password" %>
                </div>
                <div class="input-group">
                  <div class="input-group-prepend">
                    <div class="input-group-text">
                      <i class="tim-icons icon-lock-circle"></i>
                    </div>
                  </div>
                  <%= password_field :user, :password_confirmation, autocomplete: "current-password", class:"form-control", placeholder: "Password confirmation" %>
                </div>
              </div>
            </form>
          </div>
          <div class="card-footer">
            <%= submit_tag "Sign up", class: "btn btn-primary btn-round btn-lg mr-4" %>
            <a href="/users/sign_in" class="text-black">I'm a user</a>
          </div>
        </div>
      </div>
    </div>
</div>
<% end %>